version: '3.8'

services:
  front-end:
    depends_on: 
     - back-end
    image: react-docker:latest
    ports:
     - 5173:5173

  back-end:
    image: com/shop_backend
    ports:
      - 8080:8080
